<?php
/**
 * Created by PhpStorm.
 * User: feng
 * Date: 2020/4/11
 * Time: 21:14
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Craftsman extends Model
{
    use SoftDeletes;

    protected $table = 'craftsmans';

    protected $primaryKey = 'id';

    protected $fillable = [
        'username',
        'mobile',
        'unit_name',
        'bank_card',
        'bank_username',
        'bank_name',
        'from',
        'describe',
        'photo',
        'star',
        'photo',
        'video',
        'image',
        'honor',
        'describe',
        'check_status',
        'browse_amount',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('system_version', function (Builder $builder) {
            //$builder->where('system_version', 'by');
            //$builder->where('created_at', '>', '2020-04-15 00:00:00');
        });
    }

//    public function getPhotoAttribute($value)
//    {
//        if (strpos(env('APP_URL', 'http://localhost'),$value) === false) {
//            return env('APP_URL', 'http://localhost').'/'.$value;
//        }
//        return $value;
//    }
}