<?php
/**
 * Created by PhpStorm.
 * User: feng
 * Date: 2020/4/12
 * Time: 23:39
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class HistoryCraftsman extends Model
{
    use SoftDeletes;

    protected $table = 'craftsman_previous';

    protected $primaryKey = 'id';

    protected $fillable = [
        'username',
        'unit_name',
        'mobile',
        'years',
        'describe',
        'photo',
    ];

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::addGlobalScope('system_version', function (Builder $builder) {
//            $builder->where('created_at', '<', '2020-04-06 00:00:00');
//        });
//    }

//    public function getPhotoAttribute($value)
//    {
//        if (strpos(env('APP_URL', 'http://localhost'),$value) === false) {
//            return env('APP_URL', 'http://localhost').'/'.$value;
//        }
//        return $value;
//    }
}