<?php
/**
 * Created by PhpStorm.
 * User: ccoo12
 * Date: 2020/4/14
 * Time: 13:11
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class UnitSection extends Model
{
    protected $table = 'unit_section';

    protected $primaryKey = 'id';

    protected $fillable = [
        'unit_id',
        'section',
        'duty',
        'section_lead',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('system_version', function (Builder $builder) {
            //$builder->where('system_version', 'cqzgh');
        });
    }
}