<?php
/**
 * Created by PhpStorm.
 * User: ccoo12
 * Date: 2020/4/14
 * Time: 13:04
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class UnitLeader extends Model
{
    protected $table = 'unit_leader';

    protected $primaryKey = 'id';

    protected $fillable = [
        'organization_id',
        'name',
        'phone',
        'position',
        'duty'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('system_version', function (Builder $builder) {
            //$builder->where('system_version', 'cqzgh');
        });
    }
}